scripts:
      - name: Install dependencies
        script: flutter packages pub get
      - name: Install CocoaPods
        script: | 
          cd ios
          pod install
      - name: Build iOS IPA
        script: flutter build ios --release --no-codesign
